### ISSUE TITLE
Invalid Holiday received

### ISSUE THREAD

**Issue by DerGary** [rikroe/cometblue-custom-component#2]
Hello @rikroe 

I thought I open a new Issue for that. I encountered another error a few weeks ago, which I resolved by ignoring the error in code, but after updating to the newest version, my change is not in the code anymore, therefore I encountered it again and thought I report it here.

On some of my thermostats I encounter the error Invalid Holiday received:
![image](https://github.com/user-attachments/assets/e0986291-a378-4197-ab45-b27c63e33955)

After that I tried to change the holiday settings of the thermostats through the eurotronic smartphone app which worked for some of them but some still reported that error. After that, because I don't use that feature I did the following code change:

https://github.com/rikroe/cometblue-custom-component/commit/d9816595ae131885aac8362774c1e325dbd68b96

Unfortunately there is nothing in the error log for that error

**Comment by rikroe** [comment]
This basically means that your TRVs are reporting a VERY weird holiday - maybe none was ever set?

For reference, the returned data is as follows:
```
>>> values
bytearray(b'\xe0\xe0\x00\xe0\xe0\xa5\xa5\xe0\xe0')
>>> [int(i) for i in values]
[224, 224, 0, 224, 224, 165, 165, 224, 224]
```
If the error would not be raised, this would be parsed (or failed to parse) by https://github.com/rikroe/eurotronic-cometblue/blob/ha-component/cometblue/__init__.py#L336-L356 as follows:
```
start = datetime(2224, 0, 224, 224)  # 2224-00-224 224:00
```

Do you want to try [20241111.1](https://github.com/rikroe/cometblue-custom-component/releases/tag/20241111.1)? It should only log a warning and actually initialize the component.

To fix the warning, you probably need to set one holiday (even in the past) via the `set_holiday` service, so valid data gets returned.

I've also rebuild the retry logic to retry on timeouts on connect (which it didn't do beforehand).

**Comment by rikroe** [comment]
Deleted the latest release as there some issues with it. Will check soon

**Comment by DerGary** [comment]
The Europrog app reads the holiday values as following:

Wohnzimmer:
Start: 2024.01.01 00:00
End 2000.01.01 -
Temperature: off
 
Arbeitszimmer Links:
Start: 2024.01.01 -
End: 2024.01.01 00:00
Temperature: off

Arbeitszimmer Rechts:
Start: 2024.01.01 -
End 2000.01.01 -
Temperature: off

Küche:
Start: 2024.01.01 -
End: 2024.01.01 -
Temperature: off

Maybe on the weekend when I got some more time, i will try to set them to more specific date time. But apart from that some of them do not have a time, they should be valid?

**Comment by rikroe** [comment]
Thanks! I changed the logic to discard holidays a bit (https://github.com/rikroe/eurotronic-cometblue/commit/85090d4469d961d26d3eb9952d2d793f47bdb90e) which should help this issue.

Also, https://github.com/rikroe/cometblue-custom-component/releases/tag/20241117.1 should now not fail on holidays anymore.

**Comment by DerGary** [comment]
I installed the version 20241118 right now and it seems that the invalid holiday message is gone 👍It configured all my thermostats successfully.
